In [1]:
#loading dataset
import pandas as pd
import numpy as np
#visualisation
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
#EDA
from collections import Counter
import pandas_profiling as pp
# data preprocessing
from sklearn.preprocessing import StandardScaler
# data splitting
from sklearn.model_selection import train_test_split
# data modeling
from sklearn.metrics import confusion_matrix,accuracy_score,roc_curve,classification_report,mean_absolute_error
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from xgboost import XGBClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
import sklearn.metrics as metrics
from mlxtend.classifier import StackingCVClassifier

In [2]:
df = pd.read_csv(r"C:\Users\rn599\Downloads\Monthly_Food_Retail_Prices.csv")
#for get all data without summary
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)

In [3]:
df.head()

State          Centre Commodity Variety Unit Category  \
0     Andhra Pradesh        Chittoor     Moong   Split  Kg.     Food   
1     Andhra Pradesh          Guntur     Moong   Split  Kg.     Food   
2     Andhra Pradesh         Kurnool     Moong   Split  Kg.     Food   
3     Andhra Pradesh  Vishakhapatnam     Moong   Split  Kg.     Food   
4  Arunachal Pradesh        Itanagar     Moong   Split  Kg.     Food   

       Date  Retail Price  
0  Jan-2001          24.0  
1  Jan-2001          26.0  
2  Jan-2001          25.5  
3  Jan-2001           NaN  
4  Jan-2001           NaN

In [4]:
#drop the same value columns
df = df.drop(['Category'],axis=1)

#get values after drop the duplicates rows
df2=df.drop_duplicates()

#reset index
df2.reset_index(inplace = True)

#we are taking data till 1000 index due to technical issue
#df2_dupli_drop.head(1000)

In [5]:
#like for get the string value/columns
cat_vars=df.select_dtypes(include='object')
cat_vars.head(10)

State          Centre Commodity Variety Unit      Date
0     Andhra Pradesh        Chittoor     Moong   Split  Kg.  Jan-2001
1     Andhra Pradesh          Guntur     Moong   Split  Kg.  Jan-2001
2     Andhra Pradesh         Kurnool     Moong   Split  Kg.  Jan-2001
3     Andhra Pradesh  Vishakhapatnam     Moong   Split  Kg.  Jan-2001
4  Arunachal Pradesh        Itanagar     Moong   Split  Kg.  Jan-2001
5              Assam       Dibrugarh     Moong   Split  Kg.  Jan-2001
6              Assam          Dispur     Moong   Split  Kg.  Jan-2001
7              Assam        Guwahati     Moong   Split  Kg.  Jan-2001
8              Assam         Silchar     Moong   Split  Kg.  Jan-2001
9              Bihar            Gaya     Moong   Split  Kg.  Jan-2001

In [6]:
miss_val_per = cat_vars.isnull().mean()*100
miss_val_per

State         0.000000
Centre        0.000000
Commodity     0.852490
Variety      18.002623
Unit          0.000000
Date          0.000000
dtype: float64

In [7]:
#we will get the name of columns where missing value percentage >0 
isnull_per = cat_vars.isnull().mean()*100
miss_vars=isnull_per[isnull_per>0].keys()
miss_vars

Index(['Commodity', 'Variety'], dtype='object')

In [8]:
##for fill the missing value accordding to mode() value      //for more columns
for var in miss_vars:
    dff = cat_vars[var].fillna(cat_vars[var].mode()[0],inplace = True)
    print(var,"=",cat_vars[var].mode()[0])

Commodity = Rice
Variety = FAQ


In [9]:
#do for check the null values is in it or not
cat_vars.isnull().sum()

State        0
Centre       0
Commodity    0
Variety      0
Unit         0
Date         0
dtype: int64

In [10]:
#like for get the float/int value/columns
cat_vars_num=df.select_dtypes(include=['int64','float64'])
cat_vars_num.head(10)

Retail Price
0          24.0
1          26.0
2          25.5
3           NaN
4           NaN
5           NaN
6           NaN
7           NaN
8           NaN
9           NaN

In [11]:
#get parcentage of missing value in int and float columns
miss_val_per1 = cat_vars_num.isnull().mean()*100
miss_val_per1

Retail Price    50.006914
dtype: float64

In [12]:
#for get variable where values is missing according to candition
missing_num_var2=miss_val_per1[miss_val_per1>0].keys()
missing_num_var2

Index(['Retail Price'], dtype='object')

In [13]:
# we have all types of commodity
a=['Apple', 'Arhar', 'Atta','Bajra', 'Banana', 'Besan', 'Biscuit', 'Black Pepper','Bread','Brinjal','Butter','Chicken','Coconut','Coconut Oil',
'Coffee','Coriander','Cummin Seed','Eggs','Fish','Ghee','Gingelly Oil','Gram','Groundnut Oil','Gur',             
'Jowar','Maida','Maize','Masur','Meat','Milk', 'Moong','Mustard Oil','Onion','Potato','Ragi','Red Chillies',     
'Rice','Salt','Sugar','Suji','Tea','Tomato','Turmeric','Urad','Vanaspati','Wheat']
for i in a:
    filtered_values1 = df[(df.Commodity==i)]
    dff1 = filtered_values1['Retail Price'].fillna(filtered_values1['Retail Price'].median(),inplace = True)
    df.update(filtered_values1)

C:\Users\rn599\AppData\Local\Temp\ipykernel_16432\2464168419.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dff1 = filtered_values1['Retail Price'].fillna(filtered_values1['Retail Price'].median(),inplace = True)
C:\Users\rn599\AppData\Local\Temp\ipykernel_16432\2464168419.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dff1 = filtered_values1['Retail Price'].fillna(filtered_values1['Retail Price'].median(),inplace = True)
C:\Users\rn599\AppData\Local\Temp\ipykernel_16432\2464168419.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the document

C:\Users\rn599\AppData\Local\Temp\ipykernel_16432\2464168419.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dff1 = filtered_values1['Retail Price'].fillna(filtered_values1['Retail Price'].median(),inplace = True)
C:\Users\rn599\AppData\Local\Temp\ipykernel_16432\2464168419.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dff1 = filtered_values1['Retail Price'].fillna(filtered_values1['Retail Price'].median(),inplace = True)
C:\Users\rn599\AppData\Local\Temp\ipykernel_16432\2464168419.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the document

C:\Users\rn599\AppData\Local\Temp\ipykernel_16432\2464168419.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dff1 = filtered_values1['Retail Price'].fillna(filtered_values1['Retail Price'].median(),inplace = True)
C:\Users\rn599\AppData\Local\Temp\ipykernel_16432\2464168419.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dff1 = filtered_values1['Retail Price'].fillna(filtered_values1['Retail Price'].median(),inplace = True)
C:\Users\rn599\AppData\Local\Temp\ipykernel_16432\2464168419.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the document

In [14]:
#we got the final data after missing value handling
df['Retail Price'] = df['Retail Price'].astype(int)

In [15]:
display(df.dtypes)

State           object
Centre          object
Commodity       object
Variety         object
Unit            object
Date            object
Retail Price     int32
dtype: object

In [16]:
df["Variety"] = df["Variety"].fillna("FAQ")

In [17]:
df.isnull().sum()

State           0
Centre          0
Commodity       0
Variety         0
Unit            0
Date            0
Retail Price    0
dtype: int64

In [18]:
df.head(200)

State          Centre    Commodity Variety      Unit  \
0       Andhra Pradesh        Chittoor        Moong   Split       Kg.   
1       Andhra Pradesh          Guntur        Moong   Split       Kg.   
2       Andhra Pradesh         Kurnool        Moong   Split       Kg.   
3       Andhra Pradesh  Vishakhapatnam        Moong   Split       Kg.   
4    Arunachal Pradesh        Itanagar        Moong   Split       Kg.   
5                Assam       Dibrugarh        Moong   Split       Kg.   
6                Assam          Dispur        Moong   Split       Kg.   
7                Assam        Guwahati        Moong   Split       Kg.   
8                Assam         Silchar        Moong   Split       Kg.   
9                Bihar            Gaya        Moong   Split       Kg.   
10               Bihar         Hajipur        Moong   Split       Kg.   
11               Bihar     Muzaffarpur        Moong   Split       Kg.   
12               Bihar           Patna        Moong   Split       Kg.   
13                 Goa          Panaji        Moong   Split       Kg.   
14             Gujarat    Gandhi Nagar        Moong   Split       Kg.   
15             Gujarat          Rajkot        Moong   Split       Kg.   
16             Gujarat           Surat        Moong   Split       Kg.   
17             Gujarat         Vadodra        Moong   Split       Kg.   
18             Haryana          Hissar        Moong   Split       Kg.   
19             Haryana          Karnal        Moong   Split       Kg.   
20    Himachal Pradesh           Mandi        Moong   Split       Kg.   
21    Himachal Pradesh          Shimla        Moong   Split       Kg.   
22       Jammu Kashmir           Jammu        Moong   Split       Kg.   
23       Jammu Kashmir       Shrinagar        Moong   Split       Kg.   
24           Jharkhand         Dhanbad        Moong   Split       Kg.   
25           Jharkhand          Ranchi        Moong   Split       Kg.   
26           Karnataka       Bangalore        Moong   Split       Kg.   
27           Karnataka         Bijapur        Moong   Split       Kg.   
28           Karnataka           Hubli        Moong   Split       Kg.   
29           Karnataka          Tumkur        Moong   Split       Kg.   
30              Kerala       Ernakulam        Moong   Split       Kg.   
31              Kerala      Khozhikode        Moong   Split       Kg.   
32              Kerala      Trivandrum        Moong   Split       Kg.   
33      Madhya Pradesh         Bhillai        Moong   Split       Kg.   
34      Madhya Pradesh          Bhopal        Moong   Split       Kg.   
35      Madhya Pradesh         Gwalior        Moong   Split       Kg.   
36      Madhya Pradesh          Indore        Moong   Split       Kg.   
37      Madhya Pradesh            Rewa        Moong   Split       Kg.   
38      Madhya Pradesh          Sehore        Moong   Split       Kg.   
39         Maharashtra      Aurangabad        Moong   Split       Kg.   
40         Maharashtra          Mumbai        Moong   Split       Kg.   
41         Maharashtra          Nagpur        Moong   Split       Kg.   
42         Maharashtra           Nasik        Moong   Split       Kg.   
43         Maharashtra            Pune        Moong   Split       Kg.   
44             Manipur          Imphal        Moong   Split       Kg.   
45           Meghalaya        Shillong        Moong   Split       Kg.   
46             Mizoram          Aizwal        Moong   Split       Kg.   
47            Nagaland          Kohima        Moong   Split       Kg.   
48    National Capital           Delhi        Moong   Split       Kg.   
49              Orissa    Bhawanipatna        Moong   Split       Kg.   
50              Orissa     Bhubneshwar        Moong   Split       Kg.   
51              Orissa         Cuttack        Moong   Split       Kg.   
52              Punjab        Amritsar        Moong   Split       Kg.   
53              Punjab        Bhatinda        Moong   Split       Kg.   
54

In [19]:
from sklearn.preprocessing import LabelEncoder
labelencoder=LabelEncoder()
for col in cat_vars.columns :
    df[col] = labelencoder.fit_transform(df[col])
 
df.head()

State  Centre  Commodity  Variety  Unit  Date  Retail Price
0      1      16         30       26     7    81            24
1      1      29         30       26     7    81            26
2      1      50         30       26     7    81            25
3      1      85         30       26     7    81            70
4      2      40         30       26     7    81            70

In [20]:
b = df["Commodity"].unique()

In [21]:
X=df.drop('Retail Price', axis=1)

y=df['Retail Price']

In [22]:
print("X=",X.shape,"\ny=", y.shape)

X= (1048575, 6) 
y= (1048575,)


In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=0)

## K-NeighborsClassifier

In [36]:
m5 = 'K-NeighborsClassifier'
knn = KNeighborsClassifier(n_neighbors=10)
knn.fit(X_train, y_train)
knn_predicted = knn.predict(X_test)
knn_conf_matrix = confusion_matrix(y_test, knn_predicted)
knn_acc_score = accuracy_score(y_test, knn_predicted)
print("confussion matrix")
print(knn_conf_matrix)
print("\n")
print("Accuracy of K-NeighborsClassifier:",knn_acc_score*100,'\n')
print(classification_report(y_test,knn_predicted))

confussion matrix
[[ 0  0  0 ...  0  0  0]
 [ 0 19  7 ...  0  0  0]
 [ 0  7 69 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]


Accuracy of K-NeighborsClassifier: 45.00753399835969 

              precision    recall  f1-score   support

           1       0.00      0.00      0.00         1
           2       0.21      0.15      0.18       123
           3       0.35      0.25      0.29       276
           4       0.29      0.21      0.24       382
           5       0.59      0.75      0.66      1580
           6       0.17      0.16      0.16       687
           7       0.37      0.36      0.36      1064
           8       0.14      0.14      0.14      1042
           9       0.63      0.80      0.70      3162
          10       0.26      0.28      0.27      2037
          11       0.13      0.06      0.08       544
          12       0.15      0.13      0.14      1506
          13       0.25      0.31      0.28      1598
          14

C:\Users\rn599\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\rn599\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\rn599\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average,

## dicision tree

In [37]:
m6 = 'DecisionTreeClassifier'
dt = DecisionTreeClassifier(criterion = 'entropy',random_state=0,max_depth = 6)
dt.fit(X_train, y_train)
dt_predicted = dt.predict(X_test)
dt_conf_matrix = confusion_matrix(y_test, dt_predicted)
dt_acc_score = accuracy_score(y_test, dt_predicted)
print("confussion matrix")
print(dt_conf_matrix)
print("\n")
print("Accuracy of DecisionTreeClassifier:",dt_acc_score*100,'\n')
print(classification_report(y_test,dt_predicted))

confussion matrix
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


Accuracy of DecisionTreeClassifier: 49.1598161322932 

              precision    recall  f1-score   support

           1       0.00      0.00      0.00         1
           2       0.00      0.00      0.00       123
           3       0.00      0.00      0.00       276
           4       0.00      0.00      0.00       382
           5       0.61      0.75      0.67      1580
           6       0.00      0.00      0.00       687
           7       0.64      0.22      0.33      1064
           8       0.00      0.00      0.00      1042
           9       0.55      0.77      0.64      3162
          10       0.39      0.17      0.24      2037
          11       0.00      0.00      0.00       544
          12       0.00      0.00      0.00      1506
          13       0.00      0.00      0.00      1598
          14       0.00      0.00      0.00     

C:\Users\rn599\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\rn599\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\rn599\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average,

## naive bayes

In [29]:
m2 = 'Naive Bayes'
nb = GaussianNB()
nb.fit(X_train,y_train)
nbpred = nb.predict(X_test)
nb_conf_matrix = confusion_matrix(y_test, nbpred)
nb_acc_score = accuracy_score(y_test, nbpred)
print("confussion matrix")
print(nb_conf_matrix)
print("\n")
print("Accuracy of Naive Bayes model:",nb_acc_score*100,'\n')
print(classification_report(y_test,nbpred))

confussion matrix
[[ 0  0  0 ...  0  0  0]
 [ 0 74  0 ...  0  0  0]
 [ 0 96  0 ...  0  0  0]
 ...
 [ 0  0  0 ...  5  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]


Accuracy of Naive Bayes model: 20.03147128245476 



C:\Users\danis\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\danis\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\danis\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifie

              precision    recall  f1-score   support

           1       0.00      0.00      0.00         3
           2       0.08      0.28      0.12       263
           3       0.00      0.00      0.00       565
           4       0.00      0.00      0.00       769
           5       0.30      0.77      0.43      3229
           6       0.00      0.00      0.00      1400
           7       0.00      0.00      0.00      2132
           8       0.00      0.00      0.00      2132
           9       0.51      0.69      0.59      6354
          10       0.00      0.00      0.00      4037
          11       0.00      0.00      0.00      1066
          12       0.00      0.00      0.00      2984
          13       0.00      0.00      0.00      3180
          14       0.00      0.00      0.00      1984
          15       0.46      0.09      0.15      6283
          16       0.26      0.25      0.26      7770
          17       0.00      0.00      0.00      3167
          18       0.00    

C:\Users\danis\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\danis\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## Random Forest Classfier

In [31]:
m3 = 'Random Forest Classfier'
rf = RandomForestClassifier(n_estimators=20, random_state=12,max_depth=5)
rf.fit(X_train,y_train)
rf_predicted = rf.predict(X_test)
rf_conf_matrix = confusion_matrix(y_test, rf_predicted)
rf_acc_score = accuracy_score(y_test, rf_predicted)
print("confussion matrix")
print(rf_conf_matrix)
print("\n")
print("Accuracy of Random Forest:",rf_acc_score*100,'\n')
print(classification_report(y_test,rf_predicted))

confussion matrix
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


Accuracy of Random Forest: 38.23760818253344 



C:\Users\danis\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\danis\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

           1       0.00      0.00      0.00         3
           2       0.00      0.00      0.00       263
           3       0.00      0.00      0.00       565
           4       0.00      0.00      0.00       769
           5       0.60      0.77      0.67      3229
           6       0.00      0.00      0.00      1400
           7       0.65      0.23      0.34      2132
           8       0.00      0.00      0.00      2132
           9       0.28      0.87      0.43      6354
          10       0.00      0.00      0.00      4037
          11       0.00      0.00      0.00      1066
          12       0.00      0.00      0.00      2984
          13       0.00      0.00      0.00      3180
          14       0.00      0.00      0.00      1984
          15       0.47      0.31      0.37      6283
          16       0.30      0.76      0.43      7770
          17       0.00      0.00      0.00      3167
          18       0.53    

C:\Users\danis\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## svc

In [26]:
from keras.models import Sequential
model = Sequential()
model.compile(loss='mae', optimizer='adam')
model.fit(X_train,y_train)

26215/26215 [==============================] - 36s 1ms/step - loss: 75.8459


In [ ]:
model_predicted = model.predict(X_test)
model_conf_matrix = confusion_matrix(y_test, model_predicted)
model_acc_score = accuracy_score(y_test, model_predicted)
print("confussion matrix")
print(model_conf_matrix)
print("\n")
print("Accuracy of Random Forest:",model_acc_score*100,'\n')
print(classification_report(y_test,model_predicted))

In [27]:
model_predicted = model.predict(X_test)

In [28]:
cutoff = 0.7                              # decide on a cutoff limit
y_pred_classes = np.zeros_like(model_predicted)    # initialise a matrix full with zeros
y_pred_classes[model_predicted > cutoff] = 1

In [29]:
y_test_classes = np.zeros_like(model_predicted)
y_test_classes[model_predicted > cutoff] = 1

In [31]:
model_conf_matrix=confusion_matrix(y_test_classes.argmax(axis=1), y_pred_classes.argmax(axis=1))

In [32]:
model_conf_matrix

array([[209715]], dtype=int64)

In [33]:
model_acc_score = accuracy_score(y_test_classes, y_pred_classes)

In [34]:
print("Accuracy of Extreme Gradient Boost:",model_acc_score*100,'\n')

Accuracy of Extreme Gradient Boost: 100.0 



## K-NeighborsClassifier according to commodity

In [24]:
# we have all types of commodityhttp://localhost:8888/notebooks/RR%20Regssaion.ipynb#K-NeighborsClassifier-according-to-commodity
for i in b:
    filtered_values1 = df[(df.Commodity==i)]
    
    X1=filtered_values1.drop('Retail Price', axis=1)
    y1=filtered_values1['Retail Price']
    
    X_train, X_test, y_train, y_test = train_test_split(X1, y1, test_size=0.2, random_state=0)
    
    m5 = 'K-NeighborsClassifier'
    knn = KNeighborsClassifier(n_neighbors=10)
    
    knn.fit(X_train, y_train)
    
    knn_predicted = knn.predict(X_test)
    knn_conf_matrix = confusion_matrix(y_test, knn_predicted)
    knn_acc_score = accuracy_score(y_test, knn_predicted)
    
    print(i)
    print("Accuracy of K-NeighborsClassifier:",knn_acc_score*100,'\n')
#     print(classification_report(y_test,knn_predicted))
    MAE= metrics.mean_absolute_error(y_test, knn_predicted)
    MSE=metrics.mean_squared_error(y_test, knn_predicted)
    RMSE= np.sqrt(MSE)
    
    print("actual price \n",y_test.head())
    print("predicted price \n",knn_predicted)
    
    print("MAE= ", MAE)
    print("MSE= ", MSE)
    print("RMSE= ", RMSE)
    print("\n")
    
#     print(filtered_values1.head())

30
Accuracy of K-NeighborsClassifier: 43.86347131445171 

actual price 
 266116    76
130532    60
95447     56
100447    50
3805      70
Name: Retail Price, dtype: int32
predicted price 
 [90 48 47 ... 70 70 70]
MAE=  13.683611716291455
MSE=  485.3606874848705
RMSE=  22.03090301110852


36
Accuracy of K-NeighborsClassifier: 49.0727029123475 

actual price 
 709553    120
225252     28
229126     26
49632      28
285473    110
Name: Retail Price, dtype: int32
predicted price 
 [28 28 28 ... 28 14 15]
MAE=  9.983851632465976
MSE=  1332.7526267541075
RMSE=  36.506884648708485


31
Accuracy of K-NeighborsClassifier: 47.88186879690148 

actual price 
 266202    98
130618    64
95533     65
100533    60
3891      89
Name: Retail Price, dtype: int32
predicted price 
 [105  64  65 ...  89  89  89]
MAE=  13.121520213023482
MSE=  531.7392883079158
RMSE=  23.059472854077036


32
Accuracy of K-NeighborsClassifier: 45.19486807068506 

actual price 
 266288    20
130704    13
95619     10
100619   

18
Accuracy of K-NeighborsClassifier: 67.21599219892735 

actual price 
 784990    140
779394    140
636277    140
736714    140
641146    140
Name: Retail Price, dtype: int32
predicted price 
 [140 140 140 ... 140 140 140]
MAE=  32.42827888834715
MSE=  9131.722866894197
RMSE=  95.56004848729513


19
Accuracy of K-NeighborsClassifier: 46.240509429341174 

actual price 
 661424    200
739272    290
645387    160
707982    230
691920    210
Name: Retail Price, dtype: int32
predicted price 
 [290 290 290 ... 290 290 290]
MAE=  66.45897624295861
MSE=  13365.13788880725
RMSE=  115.6076895747305


20
Accuracy of K-NeighborsClassifier: 60.31378600823045 

actual price 
 708097    112
686356    112
746634    200
821266    112
712114    112
Name: Retail Price, dtype: int32
predicted price 
 [112 112 112 ... 112 112 112]
MAE=  19.93287037037037
MSE=  1831.1206275720165
RMSE=  42.79159529127205


21
Accuracy of K-NeighborsClassifier: 45.66985645933014 

actual price 
 812517    62
737086    44
81

## 'DecisionTreeClassifier' according to commodity

In [25]:
for i in b:
    filtered_values1 = df[(df.Commodity==i)]
    
    X1=filtered_values1.drop('Retail Price', axis=1)
    y1=filtered_values1['Retail Price']
    X_train, X_test, y_train, y_test = train_test_split(X1, y1, test_size=0.2, random_state=0)
    
    m6 = 'DecisionTreeClassifier'
    dt = DecisionTreeClassifier(criterion = 'entropy',random_state=0,max_depth = 6)
    
    dt.fit(X_train, y_train)
    dt_predicted = dt.predict(X_test)
    dt_conf_matrix = confusion_matrix(y_test, dt_predicted)
    dt_acc_score = accuracy_score(y_test, dt_predicted)
    
    print(i)
    print("Accuracy of DecisionTreeClassifier:",dt_acc_score*100,'\n')
    
    MAE= metrics.mean_absolute_error(y_test, dt_predicted)
    MSE=metrics.mean_squared_error(y_test, dt_predicted)
    RMSE= np.sqrt(MSE)
    
    print("actual price \n",y_test.head())
    print("predicted price \n",knn_predicted)
    
    print("MAE= ", MAE)
    print("MSE= ", MSE)
    print("RMSE= ", RMSE)
    print("\n")

30
Accuracy of DecisionTreeClassifier: 45.31590413943355 

actual price 
 266116    76
130532    60
95447     56
100447    50
3805      70
Name: Retail Price, dtype: int32
predicted price 
 [9 9 9 ... 9 9 9]
MAE=  14.316872427983538
MSE=  514.1561365286856
RMSE=  22.675011279571297


36
Accuracy of DecisionTreeClassifier: 49.48875255623722 

actual price 
 709553    120
225252     28
229126     26
49632      28
285473    110
Name: Retail Price, dtype: int32
predicted price 
 [9 9 9 ... 9 9 9]
MAE=  10.510119173542064
MSE=  1365.8732106339469
RMSE=  36.95772193512401


31
Accuracy of DecisionTreeClassifier: 48.68070685064149 

actual price 
 266202    98
130618    64
95533     65
100533    60
3891      89
Name: Retail Price, dtype: int32
predicted price 
 [9 9 9 ... 9 9 9]
MAE=  14.069232631324134
MSE=  585.9235052045509
RMSE=  24.20585683681846


32
Accuracy of DecisionTreeClassifier: 46.30839990317114 

actual price 
 266288    20
130704    13
95619     10
100619    25
3977      16
Na

18
Accuracy of DecisionTreeClassifier: 67.02096538274013 

actual price 
 784990    140
779394    140
636277    140
736714    140
641146    140
Name: Retail Price, dtype: int32
predicted price 
 [9 9 9 ... 9 9 9]
MAE=  34.55894685519259
MSE=  9491.866406630912
RMSE=  97.42621005987512


19
Accuracy of DecisionTreeClassifier: 47.3426402155278 

actual price 
 661424    200
739272    290
645387    160
707982    230
691920    210
Name: Retail Price, dtype: int32
predicted price 
 [9 9 9 ... 9 9 9]
MAE=  74.37962282635317
MSE=  15371.541513592947
RMSE=  123.9820209288143


20
Accuracy of DecisionTreeClassifier: 60.95679012345679 

actual price 
 708097    112
686356    112
746634    200
821266    112
712114    112
Name: Retail Price, dtype: int32
predicted price 
 [9 9 9 ... 9 9 9]
MAE=  20.779835390946502
MSE=  1888.0036008230452
RMSE=  43.45116340010984


21
Accuracy of DecisionTreeClassifier: 45.430622009569376 

actual price 
 812517    62
737086    44
810927    58
734757    44
654376 